# Auto-generated by Roxzned Setup Designer
# This is a standalone installer script. Compile it with PyInstaller if you want.
# Requires: PySide6

import os
import sys
import json
import zipfile
import traceback

from PySide6.QtCore import Qt, Signal, QThread
from PySide6.QtWidgets import (
    QApplication, QWizard, QWizardPage, QLabel, QLineEdit, QPushButton, QHBoxLayout,
    QVBoxLayout, QTextEdit, QCheckBox, QFileDialog, QMessageBox, QProgressBar, QWidget
)

PROJECT = {
  "app_name": "Vidplayer",
  "version": "2.0.9.1",
  "publisher": "sonic Fan Tech",
  "default_install_dir": "%LOCALAPPDATA%\\VidPlayer",
  "source_folder": "E:/Projects/Project USB/VS Code/Python/Roxzned Setup installer Designer/Source/data",
  "payload_zip": "E:/Projects/Project USB/VS Code/Python/Roxzned Setup installer Designer/Source/payload.zip",
  "license_text": "put EULA Here",
  "pages": [
    {
      "title": "Welcome",
      "role": "welcome",
      "bg": {
        "color": "#151515",
        "image": ""
      },
      "items": [
        {
          "type": "Label",
          "name": "lblTitle",
          "text": "Welcome to the Setup Wizard for Vidplayer v2.0.9.1",
          "x": 24,
          "y": 24,
          "w": 520,
          "h": 36,
          "extra": {
            "font_size": 10,
            "bold": False,
            "fg": "#ffffff",
            "bg": "#00000000"
          }
        },
        {
          "type": "Label",
          "name": "lblBody",
          "text": "This Setup Wizard will setup and install Vidplayer onto your computer, Press the next Button to start",
          "x": 24,
          "y": 74,
          "w": 680,
          "h": 50,
          "extra": {
            "font_size": 10,
            "bold": False,
            "fg": "#ffffff",
            "bg": "#00000000"
          }
        }
      ]
    },
    {
      "title": "License Agreement",
      "role": "license",
      "bg": {
        "color": "#151515",
        "image": ""
      },
      "items": [
        {
          "type": "Label",
          "name": "lblLic",
          "text": "Please read the license agreement below:",
          "x": 24,
          "y": 24,
          "w": 380,
          "h": 24,
          "extra": {
            "font_size": 10,
            "bold": True,
            "fg": "#ffffff",
            "bg": "#00000000"
          }
        },
        {
          "type": "Label",
          "name": "lblHint",
          "text": "(Demo) The real installer shows a scrollable license box here.",
          "x": 24,
          "y": 56,
          "w": 520,
          "h": 24,
          "extra": {
            "font_size": 10,
            "bold": False,
            "fg": "#cfcfcf",
            "bg": "#00000000"
          }
        },
        {
          "type": "CheckBox",
          "name": "chkAgree",
          "text": "I accept the agreement",
          "x": 24,
          "y": 98,
          "w": 260,
          "h": 20,
          "extra": {
            "font_size": 10,
            "bold": False,
            "fg": "#ffffff",
            "bg": "#00000000",
            "checked": False
          }
        }
      ]
    },
    {
      "title": "Choose Install Location",
      "role": "path",
      "bg": {
        "color": "#151515",
        "image": ""
      },
      "items": [
        {
          "type": "Label",
          "name": "lblPath",
          "text": "Choose where you want to install the program:",
          "x": 24,
          "y": 24,
          "w": 420,
          "h": 24,
          "extra": {
            "font_size": 10,
            "bold": True,
            "fg": "#ffffff",
            "bg": "#00000000"
          }
        },
        {
          "type": "EditBox",
          "name": "txtPath",
          "text": "%LOCALAPPDATA%\\VidPlayer",
          "x": 24,
          "y": 60,
          "w": 420,
          "h": 26,
          "extra": {
            "font_size": 10,
            "bold": False,
            "fg": "#ffffff",
            "bg": "#111111"
          }
        },
        {
          "type": "Button",
          "name": "btnSetPath",
          "text": "Set Path",
          "x": 454,
          "y": 60,
          "w": 92,
          "h": 26,
          "extra": {
            "font_size": 10,
            "bold": False,
            "fg": "#ffffff",
            "bg": "#232323"
          }
        },
        {
          "type": "CheckBox",
          "name": "chkDesktop",
          "text": "Make Desktop shortcut",
          "x": 24,
          "y": 100,
          "w": 220,
          "h": 20,
          "extra": {
            "font_size": 10,
            "bold": False,
            "fg": "#ffffff",
            "bg": "#00000000",
            "checked": True
          }
        }
      ]
    },
    {
      "title": "Installing",
      "role": "installing",
      "bg": {
        "color": "#151515",
        "image": ""
      },
      "items": [
        {
          "type": "Label",
          "name": "lblInst",
          "text": "Installing...",
          "x": 24,
          "y": 24,
          "w": 200,
          "h": 24,
          "extra": {
            "font_size": 10,
            "bold": True,
            "fg": "#ffffff",
            "bg": "#00000000"
          }
        },
        {
          "type": "Label",
          "name": "lblInst2",
          "text": "(Demo) Files will be packed + extracted here.",
          "x": 24,
          "y": 54,
          "w": 380,
          "h": 24,
          "extra": {
            "font_size": 10,
            "bold": False,
            "fg": "#cfcfcf",
            "bg": "#00000000"
          }
        }
      ]
    },
    {
      "title": "Finish",
      "role": "finish",
      "bg": {
        "color": "#151515",
        "image": ""
      },
      "items": [
        {
          "type": "Label",
          "name": "lblDone",
          "text": "Setup is complete.",
          "x": 24,
          "y": 24,
          "w": 220,
          "h": 24,
          "extra": {
            "font_size": 10,
            "bold": True,
            "fg": "#ffffff",
            "bg": "#00000000"
          }
        },
        {
          "type": "CheckBox",
          "name": "chkLaunch",
          "text": "Launch Vidplayer",
          "x": 24,
          "y": 60,
          "w": 200,
          "h": 20,
          "extra": {
            "font_size": 10,
            "bold": False,
            "fg": "#ffffff",
            "bg": "#00000000",
            "checked": True
          }
        }
      ]
    }
  ]
}

# (Demo) Real build will generate full UI + install/uninstall logic.
# • Pages: Welcome / License / Path / Installing / Finish
# • Widgets: Text, Button, CheckBox, Image, EditBox
# • Actions: Back/Next/Close/Open URL/Set Path
# • Packing: payload.zip -> install dir

if __name__ == '__main__':
    print('Demo: generated script preview only')
